name: Buscar Passagens

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 🔥 Instala ODBC Driver 18 corretamente no Linux
      - name: Install ODBC Driver 18
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg unixodbc-dev
          
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list \
          | sudo tee /etc/apt/sources.list.d/mssql-release.list

          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      # 📦 Instala dependências Python
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🔍 Debug para garantir secrets
      - name: Debug variáveis
        env:
          SERVER: ${{secrets.SERVER}}
          DATABASE: ${{secrets.DATABASE}}
          UID: ${{secrets.UID}}
        run: |
          echo "SERVER=$SERVER"
          echo "DATABASE=$DATABASE"
          echo "UID=$UID"
          if [ -z "$PWD" ]; then echo "PWD está vazio!"; else echo "PWD recebido."; fi
      - name: Debug ODBC Drivers
        run: |
          odbcinst -q -d
          isql -v "DRIVER={ODBC Driver 18 for SQL Server};SERVER=${{secrets.SERVER}};DATABASE=${{secrets.DATABASE}};UID=${{secrets.UID}};PWD=${{secrets.PWD}};Encrypt=yes;TrustServerCertificate=no;"


      # 🚀 Executa o script FINAL
      - name: Rodar script
        env:
          SERPAPI_KEY: ${{secrets.SERPAPI_KEY}}
          EMAIL: ${{secrets.EMAIL}}
          EMAIL_DESTINO: ${{secrets.EMAIL_DESTINO}}
          APP_KEY: ${{secrets.APP_KEY}}
          SERVER: ${{secrets.Server}}
          DATABASE: ${{secrets.Database}}
          UID: ${{secrets.Uid}}
          PWD: ${{secrets.Pwd}}

          TZ: America/Sao_Paulo

        run: python src/main.py
